Handle grouped test cases + auto-retry if out of tokens
Kattis/kattis-cli pull request #49
Opened 2024-10-12 15:54 UTC by RussellDash332

# What's the problem?

Sometimes, when you're working on a question with partial scores, it is very likely that the test cases are made into groups. The current implementation hinders whether we fail the test case group(s) or not.

Here's an example I took while working on [this question](https://open.kattis.com/problems/ordla) and [this question](https://open.kattis.com/problems/sequences). Assume that `ktcli <problem_id>` is my own command alias to run the submission script along with `<problem_id>.py` attached somewhere.

Normally, if you fail a testcase, the judging will stop, as shown below.

![image](https://github.com/user-attachments/assets/cb861e77-b653-4285-a872-ca0abb1ac799)

For those with testcase groups, if you fail a testcase, instead of ending the entire judgement, there can be multiple behaviors. Usually, it will simply move on to the next testcase group, until there is none left. On other occassions, it will keep judging the next test cases anyways.

Therefore, we can't tell if we're failing a particular test case or not until we know it stops judging. In fact, we can still get partially accepted with these mistakes existing, as shown below (I did not get 100 points for this).

![image](https://github.com/user-attachments/assets/05a62a02-060e-475c-be1b-9cbe141968ab)

# So what does this PR do?

## Introduce colours (and scores too! #44)

With colours, we can finally tell these testcases apart. Here are two scenarios: when the judging is in progress, and when it's done.

### Judging in progress

Yellow question mark for a nice touch 😄

Single group (default)
![image](https://github.com/user-attachments/assets/2cb4f967-9c75-45ee-813e-71313ab314d7)

Grouped testcases
![image](https://github.com/user-attachments/assets/168d830c-8b48-45a4-bcbe-20dce3bbe608)

### AC verdict

Single group (default)
![image](https://github.com/user-attachments/assets/95d054a4-4451-4f3f-8f1c-203c304880d8)

Grouped testcases
![image](https://github.com/user-attachments/assets/4ae6bfbc-828d-4594-a967-f47a428289be)

### Non-AC verdict
![image](https://github.com/user-attachments/assets/6d0869fe-a369-44c3-9a57-343c49a72427)

## Small addition: auto-retry for out-of-tokens scenario

I personally find myself too lazy to keep running the script whenever I ran out of tokens. So I made sure that the script auto-retries until it has a token again.

- Pro: less manual work involved
- Con: more requests sent as an attempt to submit

Here's a reference to what originally happens when you're out of tokens.

![image](https://github.com/user-attachments/assets/068ab1cf-626a-426e-97c6-7210956ab395)

This PR will ensure when the same thing happens, it will simply wait until the time is right and then does the usual behavior.

2025-03-02 22:59 UTC, JoelNiemela requested changes
I added a few comments. Once those are fixed, I think this could be approved.

2025-03-02 22:59 UTC, JoelNiemela commented on submit.py
> +                    score = re.findall('\(([\d\.]+)\)', root.xpath('.//*[@data-type="status"]')[0].text_content())[0]
This line gives me this error:
```
SyntaxWarning: invalid escape sequence '\('
```

I think you want a raw-string here:
```suggestion
                    score = re.findall(r'\(([\d\.]+)\)', root.xpath('.//*[@data-type="status"]')[0].text_content())[0]
```

2025-03-02 22:59 UTC, JoelNiemela commented on submit.py
> +                    progress = progress[:10*(testcases_done - 1)] + color('?', _YELLOW_COLOR)
This part was a bit confusing until I realized that `len(color('.', ...))` is 10. Maybe a comment could be added that mentions that?

```suggestion
                    # N.b.: We need to do some weird math, since len(color('.', _SOME_COLOR)) = 10
                    progress = progress[:10*(testcases_done - 1)] + color('?', _YELLOW_COLOR)
```

2025-03-02 22:59 UTC, JoelNiemela commented on submit.py
> +                            tag)
Why did you remove `args.assignment` and `args.contest`?

2025-03-02 22:59 UTC, JoelNiemela commented on submit.py
> +        if plain_result.startswith('You are out of submission tokens.'): time.sleep(3); continue
We don't want to auto-resubmit when a user's submission tokens run out (as that could very easily lead to a lot of needless requests).

2025-03-07 08:01 UTC, RussellDash332 commented on submit.py
> +                            tag)
Whoops, let me bring this back!

2025-04-02 21:49 UTC, JoelNiemela approved these changes
Looks good! :+1:

2025-04-02 21:51 UTC, niemela approved these changes

2025-04-09 15:32 UTC, merged